<a href="https://colab.research.google.com/github/mamikah/DeepLearning2022Late/blob/main/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%A8%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E4%BD%BF%E7%94%A80920_0927.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# モジュールを使う

## import文でモジュールを読み込んで使う

In [1]:
# mathモジュール
import math
# 円周率
print(math.pi)
# 乗
print(math.pow(5,2))
# 平方根
print(math.sqrt(9))

3.141592653589793
25.0
3.0


## Numpy ---数値計算用の便利なライブラリ

https://numpy.org/

In [2]:
import numpy as np

### np配列（ndarray）を作る

In [3]:
a = np.array([5,7,3,1,4,3])
print(a)

[5 7 3 1 4 3]


### Numpyで配列の操作をしてみる

In [4]:
# 現在、aは1行1次元配列
print('初期の配列:',a)
# aを 3行2列の2次元配列に構成しなおす
b = a.reshape([3,2]) # 引数で指定
print(b)

初期の配列: [5 7 3 1 4 3]
[[5 7]
 [3 1]
 [4 3]]


In [5]:
# 3行4列の0が入った2次元配列を作る
c = np.zeros((3,4))
print(c)
# ランダムな値が入った配列を作る
np.random.seed(0)
d = np.random.rand(3,4)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


### Numpyのスライス

**基本**<br>
リストのスライスの指定の仕方 ---> [start : stop : step ]

In [6]:
l = list(range(10))
print(l)
print(l[:3])
print(l[2:])
print(l[2::3])
print(l[::-1])
print(l[-2:-9:-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2]
[2, 3, 4, 5, 6, 7, 8, 9]
[2, 5, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[8, 7, 6, 5, 4, 3, 2]


1次元のNumpy配列(ndarray)におけるスライス

In [7]:
# 範囲を指定してndarrayを作る
e = np.arange(10)
print(e)
print(e[1:8])
print(e[1:8:2])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[1 3 5 7]


### スライスでの代入

In [8]:
# 指定した範囲に特定の値を代入
print(e)
e[3:6] = 100
print(e)
e[3:6] = [100,200,300]
print(e)
e[2:8:2] = 500
print(e)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100 100 100   6   7   8   9]
[  0   1   2 100 200 300   6   7   8   9]
[  0   1 500 100 500 300 500   7   8   9]


多次元のNumpy配列(ndarray)におけるスライス

In [9]:
# 3行4列の2次元配列を作る
f = np.arange(12).reshape((3,4))
print(f)
# 2行目から終わりまでの行 = [1:]
# 1列目から3列目までの行 = [1:3]
f[1:,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 5,  6],
       [ 9, 10]])

In [10]:
g = np.arange(20).reshape((5,4))
print(g)
g[2:,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 9, 10],
       [13, 14],
       [17, 18]])

多次元のndarrayへのスライスでの代入

In [27]:
h = np.arange(12).reshape((3,4))
print(h)
# 5,6,9,10の部分をスライス
print(h[1:,1:3])
h[1:,1:3] = 100
print(h)

# 多次元での上書きにリストを使う
h[1:,1:3] = [100,200]
print(h)

# 多次元の上書きに2次元のリストを使う
h[1:,1:3] = [[100],[200]]
print(h)
h[1:,1:3] = [[100,200],[300,400]]
print(h)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[  0   1   2   3]
 [  4 100 100   7]
 [  8 100 100  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 100 200  11]]
[[  0   1   2   3]
 [  4 100 100   7]
 [  8 200 200  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 300 400  11]]


### 多次元のndarrayへのstepを使ったスライスでの代入

In [32]:
i = np.arange(12).reshape((3,4))
print(i)
print(i[1:,::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]


In [41]:
from posixpath import join
j = np.arange(12).reshape((3,4))
print(j)
print(j[:2,::3])
j[:2,::3] = 100
print(j)
j[:2,::3] = [200,300]
print(j)
j[:2,::3] = [[400],[500]]
print(j)
j[:2,::3] = [[600,700],[800,900]]
print(j)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 3]
 [4 7]]
[[100   1   2 100]
 [100   5   6 100]
 [  8   9  10  11]]
[[200   1   2 300]
 [200   5   6 300]
 [  8   9  10  11]]
[[400   1   2 400]
 [500   5   6 500]
 [  8   9  10  11]]
[[600   1   2 700]
 [800   5   6 900]
 [  8   9  10  11]]
